# Site Settings
title                    : "The Frederick Hotel"
title_separator          : "-"
name                     : "The Frederick Hotel"
description              : "Welcome to The Frederick Hotel in Tribeca, a Tribeca hotel offering boutique accommodations and timeless style in the vibrant heart of lower Manhattan."
url                      : "https://www.frederickhotelnyc.com"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "TravelTripperWeb/frederick-hotel"

# Language Settings
default_lang             : 'en'
languages                : ['en']

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - Makefile
  - media.json
  - models.json
  - node_modules
  - old_media.json
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - sitemap.json
  - tmp
  - gulpfile.js
keep_files:
  - .git
  - assets
rsync_copy:
- _assets
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
    load_paths:
        - _sass
    style: compressed

# Outputting
permalink: pretty
timezone: # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# data_paginate:
#   per_page: 5
#   data: 'blog'
#   path: 'blog/page:num'
#   pagination_template: 'blog/index.html'
#   sort_field: 'date'
#   sort_reverse: true

page_gen: #
  # - data: 'attractions'
  #   template: 'single-attraction'
  #   dir: 'attractions'
  # - data: 'blog'
  #   template: 'single-blog'
  #   dir: 'blog'
  # - data: 'events'
  #   template: 'single-event'
  #   dir: 'events'
  # - data: 'offers'
  #   template: 'single-offer'
  #   dir: 'offers'
  # - data: 'rooms'
  #   template: 'single-room'
  #   dir: 'rooms'
  # - data: 'specials'
  #   template: 'single-special'
  #   dir: 'specials'
